### ISSUE TITLE
Zip to LMDB Conversion for Datasets

### ISSUE THREAD

**Issue by SkycoinSynth** [kk-digital/stylegan2-ada-pytorch#6]
- experiment with conversion of zip file dataset to LMDB
- test use of LMDB as input, instead of a zip file

https://www.pankesh.com/_posts/2019-05-18-efficiently-storing-and-retrieving-image-datasets.html

**Comment by Volpe95** [comment]
Won't improve the performance and can't use as stream, so closing for now.
